### ISSUE TITLE
Changing PID Values in Configuration_A3ides_2209_MINI.h not possible

### ISSUE THREAD

**Issue by felixhesshaw** [prusa3d/Prusa-Firmware-Buddy#1341]
**Printer type** - [MINI]

**Printer firmware version** - [4.3.1]

**Original or Custom firmware** [Custom]

**Describe the bug**
I tried to modify my PID values because I have a bondtech heatbreak and edited the values in the config file PID Values in Configuration_A3ides_2209_MINI.h'. 
After compiling I checked the pid values with M503 and they are still the old ones.

**How to reproduce**
- edit PID Values in Configuration_A3ides_2209_MINI.h
- compile
- flash firmware
- check PID values with M503

**Expected behavior**
- new values should have been saved to the firmware

I know I can use the PID values with gcode in the slicer but I want to save them permanently. Another possible way would be to use M500 but this is also not working.

**Comment by poblopuablo** [comment]
Not sure if this will work but try this:

Re-flash firmware, then m501 (to load the setting to eeprom) then m503 to check.

**Comment by JohnnyDeer** [comment]
Hi @felixhesshaw, unfortunately this won't work because we are using our own temperatures control. Thank you for understanding.

**Comment by matthewlloyd** [comment]
I've added this feature to my unofficial Llama Mini firmware, which you can download here: https://github.com/matthewlloyd/Llama-Mini-Firmware/#readme

**Comment by SnickCH** [comment]
I disagree. I made the test with different hotends and with a new 50W heater cartridge. It makes a difference if you tune PID (with octoprint) or just let the standard as it is. The difference: with no tuning it needs a way to long time until the heat is set. At the beginning I have a long period where the heat is overshooting for 10-15degrees. To handle this, I need 4-10x skirt until the heat is down to the point it should be. The same goes for filament load / unload. 

I kindly ask to integrate this because it makes live much easier
