### ISSUE TITLE
Prusa Mini (4.3.1) reports Probing error when enterering the last probing line to the left. Emergency Stop M112 Error screen.

### ISSUE THREAD

**Issue by saysphilippe** [prusa3d/Prusa-Firmware-Buddy#1437]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

Orginal firmware 4.3.1 for Prusa Mini

No sensors added

Run with Octoprint and standalone

When probing before print it reaches the end row to the left before it halts and start beeping giving an error on the display. When pressing the wheel it restarts and it will run for a couple of times with no problem before the process start again. No adjustments have been done with PINDA or other changes. 

**How to reproduce**
This occurs randomly and can't be reproduces at least by me. 

**Expected behavior**
To complete without error and start to print :)

To view the process I have taken a video of the probing process that fails, by luck... 
Link 1: https://twitter.com/SaysPhilippe/status/1395632699042369537?s=20
Link 2: https://twitter.com/SaysPhilippe/status/1396843594095419392?s=20

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by JohnnyDeer** [comment]
Hi @saysphilippe thank you for creating issue. I wanted to ask you upload video which you already did. From video is not obvious same behavior as on MK3S right before M112 but i think that its caused by same thing, broken bed thermistor cable. Here is MK3S issue related to this one https://github.com/prusa3d/Prusa-Firmware/issues/3083. Also please contact our Tech Support for help with link to this issue (chat in right down corner https://shop.prusa3d.com/en/).

**Comment by saysphilippe** [comment]
Both Prusa and Octoprint reports Probing error, but I guess I will have to order a new bed thermistor cable, then.

**Comment by saysphilippe** [comment]
Question: Why would a bad bed thermistor cable only react when probing, and never when printing?

**Comment by JohnnyDeer** [comment]
@saysphilippe Because often cable need to be in specific angle to cause disconnect, even just for half of second. In this case end row on left side which normally is not area where you print often, isnt? May be this can also be caused by broken cable in PINDA, please discuss it with Tech Support. But definitely this is not caused by FW bug.
You don't need to order it, our Tech Support will help you :)

**Comment by Prusa-Support** [comment]
Hello @saysphilippe! Sorry for intervening on this so late. Was this issue resolved in the end through our Technical Support? Let me know, in case it's still not solved we can review it in more detail with me via email (info@prusa3d.com mentioning me "attn: Alessandro). 

Alessandro Pantaleo
Prusa Research

**Comment by bfeist** [comment]
I replaced the thermistor for my heatbed and the problem persists. M112 at the end of every print.

**Comment by Prusa-Support** [comment]
Hello! Thank you very much for the update, good to hear it is solved, sorry for this taking the unnecessary replacement and a long time. Good to have this feedback, we'll keep it in mind if we come across similar cases. 

For the future, in case of something that can be tested-troubleshot, I'd always recommend contacting us, technical support, directly: info@prusa3d.com, even me directly at that email address, mentioning me in the subject. We are trying to catch up with the threads on this GitHub, but it's meant more for development aspects.  

Alessandro Pantaleo
Prusa Research
