### ISSUE TITLE
[FEATURE REQUEST] Hide files prefixed with .

### ISSUE THREAD

**Issue by qu4cks4lb3r** [prusa3d/Prusa-Firmware-Buddy#1659]
**Printer type** - [MINI / MINI+]

**Is your feature request related to an existing problem? Please describe.**
When copying files onto the usb share, files prefixed with `.` are also created on MacOS systems. Those prefixed files with metadata are shown in the print-dialog on top whereas the don't contain any valid gcode.

eg. when copying a gcode file `dog.gcode` onto the usb drive, it will also create `._dog.gcode`. 

**Describe the expected functionality**
Hide files prefixed with a `.` in general or provide a setting to do so.

**Comment by sisuwest** [comment]
This issue only started showing up for me when I upgraded to macOS 13. Anyone else seeing this issue?

**Comment by Prusa-Support** [comment]
Hello, thank you for the report and sorry for the late response from my side on this thread. We are aware of this, we are working to improve this aspect of hidden files being shown on future releases of Prusa Slicer and FW. In case of more info from our side we'll update here. 

Alessandro Pantaleo
Prusa Research

**Comment by C44Supra** [comment]
Was this ever resolved?

**Comment by sisuwest** [comment]
Kind of. the Mini now ignores those files when inserting the USB stick. But
you can still see all of those files if they were there previously. So some
folders are messy, but new adds are clean.

**Comment by Prusa-Support** [comment]
Thank you again for reporting.

It seems this issue is not consistent among Mac users.
Not so many users reported this so far, and most reports came in a quite limited period of time, which probably means the issue no longer persists for the large majority of Mac users.

Please report your MacOS version and last update date. 
Also, please let us know your current FW version on the MINI, and if upgrading/downgrading the firmware or a factory reset helps.

For the time being, it would be safe to delete these metadata files from the USB drive. These are MacOS-specific files and have no use for the printer and slicer.
A command line via _Terminal_ (`dot_clean -m <here_add_the_path_to_the_folder>`) may help get rid of those already existing files. Otherwise, formatting the USB drive should erase it all, including hidden files.

Please report back if these secondary files will show up again after removing them, and upgrading and all-data-resetting the printer.

Michele Moramarco
Prusa Research

**Comment by C44Supra** [comment]
I'm currently running the latest version of macOS Ventura. The Mini+ is running fw 4.4.1. 

dot_clean is an option, but those files will reappear the second you plug the thumbdrive back into any mac.

**Comment by qu4cks4lb3r** [comment]
Hi,

personally it does not affect me anymore as Im using PrusaLink know. 

However, would be great for everybody using a Unix system and USB. 

Files with prefixes are hidden in Unix / Mac and this should be the same on Prusa. At least this is my suggestion. 

Daniel

**Comment by risingambitions** [comment]
I just updated to the latest Prusaslicer (2.6.0) and the latest firmware on my mini+ (4.4.1) and formatted my USB drive to get rid of anything on it. Hidden files still show up in the root folder and subfolders for me. On Mac Ventura 13.1 with M1 chip if that helps. I am also using a drive with USB-C on one end and USB-A on the other (since mac's don't have USB-A like the mini does).
