### ISSUE TITLE
[FEATURE REQUEST] Maintenance interval

### ISSUE THREAD

**Issue by Ondrashek** [prusa3d/Prusa-Firmware-Buddy#1699]
With statistics (odometer) in 4.3.3 would be great to have maintenance interval with notification and reset function. Prusa knowledge recommend do an regular maintenance each 200 print hours. 

Could be done like:
- Printer counters 200 hours of printing
- Printer gives me a notify to do an regular maintenance *
- After I am finished with maintetance I reset maintenance interval
(loop)

* The high perfection would be having notification with QR code to browse exact steps what I must do

**Comment by girak49** [comment]
I would like to renew support for this feature request. 

A maintenance reminder feature is even more valuable and necessary today now that input shaping is available. The higher accelerations puts even more stress on the printer. A quote from [Input Shaper Prusa Knowledge Base:](https://help.prusa3d.com/article/input-shaper-mk4-xl-mini-_451816) "We strongly suggest performing basic maintenance on the MK4 before you start to use the Input shaper to achieve the best possible print performance." Our cars remind us when to change the oil, I think our printers should too! :)

Here are some ideas on how this feature could be implemented:
- The reminder could pop up on printer boot-up or before a print starts if there are users who never shut off their printer
- The reminder could be dismissed because maintenance was completed or be asked to be reminded again later
- In the maintenance settings, you could look up how many print hours since last routine maintenance
- Perhaps give users the ability to reset the 200 hour clock for whatever reason.
- (and as already stated above) The reminder could have a QR code to the [maintenance website](https://help.prusa3d.com/article/regular-printer-maintenance-mk4_419000)

Thank you!
