### ISSUE TITLE
[FEATURE REQUEST] Recommend newest file in whole folder structure for printing

### ISSUE THREAD

**Issue by Sarius2009** [prusa3d/Prusa-Firmware-Buddy#2290]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [Mini+]

**Is your feature request related to a problem? Please describe.**
When popping in your USB Stick, the printer automatically opens the newest file in the root folder, for you to print it. If you use folders, it will recommend an old/done print.
  
**Describe the solution you'd like**
I would like the printer to load the newest file in the whole folder structure, not just the root one.

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.

That'd be a nice feature to have.
I guess you like to have your print files neatly organized in "thematic" folders. 🙂 

For the time being, please consider coping the file twice: in the root directory and again in the "thematic folder". You can store the copies neatly organized in folders but print from the root and the root can wipe from duplicate already printed files from time to time.
Or you may want to have a set of whole thematic USB sticks. The USB sticks don't need big storage or high speed; you don't need expensive ones for 3D printing.

Moreover, for backup and storage purposes, you may want to save your thematic folders locally on the computer and only throw print files in the USB drive's root.
This is my personal suggestion. In fact, due to intense use (prolonged activity, exposure to heat and magnetic fields, continuous unplugging...), the USB stick used for printing may not turn out to be very reliable as a storage device in the long run. 

Michele Moramarco
Prusa Research
