### ISSUE TITLE
[BUG] 4.4.0 OutOfMemory Error when loading large gcode through web interface

### ISSUE THREAD

**Issue by eddyjay** [prusa3d/Prusa-Firmware-Buddy#2802]
**Printer type** - MINI

**Printer firmware version** - 4.4.0

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
USB drive

**Describe the bug**
Created a lithophane gcode (in nature very large, about 55Mb) and uploaded through the web interface with the option to start print after upload. The file uploaded successfully, but when it was supposed to start the print a red screen with the message "Out Of Memory Error" and "malloc" in the corner. Only a reset would fix.

**How to reproduce**
Upload large gcode from web interface with option to "start after upload"

**Expected behavior**
Upload and print start

**G-code**
This g-code is of a personal nature, i'd rather not upload to a public space

**Crash dump file**
No crash dump file

**Comment by eddyjay** [comment]
> does it print when using usb or octoprint?

USB drive, but gcode uploaded from web-interface with "start after upload" selected.
I don't use octoprint.

**Comment by jrishel** [comment]
I had a similar error after checking the web interface on a print after it had started. This was the 3rd time running the print, but the first time the malloc out of memory message appeared.

**Comment by GithubUser99999999** [comment]
![IMG_20221213_010416416](https://user-images.githubusercontent.com/101017273/207189788-858dcd78-f6db-4240-9ccc-a11907724cce.jpg)

Same problem, I just finished a print and tried loading another gcode file that I had already printed a day before. I didn't even upload anything new at the moment.

The printer was set to Ethernet, but it also has an ESP-01 inside (which is just too slow).

**Comment by nebularnoise** [comment]
I experienced the same issue yesterday.

Mini: 
- firmware [4.4.1-RC1]
- connected to the network via Wifi (ESP01S)


The 22MiB gcode was upladed from PrusaSlicer to the Mini via PrusaLink, set to "start after upload".
A few minutes later, printing sarted.
After roughly 6hours of printing, I wanted to check on the status of the print through the webinterface. Because the web UI failed to load, I immediately had it checked in person, and saw this:

![signal-2022-12-19-143700_002](https://user-images.githubusercontent.com/33561374/208642719-43515dfc-df63-43c9-8b5d-fa382738889e.jpeg)

It is unclear whether the malloc failed before or after I made an HTTP request.

If it can be of any help in troubleshooting, I was printing [the following model](https://www.printables.com/model/173740-cat-stretch-voronoi-remix) using the default Prusa PLA preset, with 6 layers of raft and painted-on supports.

**Comment by Prusa-Support** [comment]
Thanks for reaching us.

As put in evidence in issues https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2351 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2612, there could be various causes of this error, such as long operation sessions, overlapping inputs and unstable connection.

While in the previous issues the problem was not always reproducible, and there are more reasons for such errors to show up, the new firmware releases could rule out some possible connection issues.

The last two firmware releases improve the connection stability and the ESP module reliability.
Please test [FW 4.4.1-RC2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.4.1-RC2) and provide feedback.

Michele Moramarco
Prusa Research

**Comment by dwbmb** [comment]
I experienced this error today too. Printed very small gcode without issues, print finished. After connecting via prusalink, printer went to this error. Printer is unreachable via prusalink since then. FW 4.4.1

**Comment by Skyfighter64** [comment]
I just experienced something very similar to the problem described by @nebularnoise:

My Setup:
Prusa Mini Firmware: 4.4.1+4194
Bootloader: 2.0.2
Additional Upgrades: Filament sensor (in use), ESP-01S WiFi Module

Printer is connected to local Network via WiFi.

Situation:
My Printer was running for about 5 hours before, was ~30min into the current print. My computer was connected to the Web Interface.

As I tried to connect to the Web Interface from my phone simultaniously (as my PC was in another room and I'm lazy xD), the Web interface kept loading indefinetly (Firefox Mobile 110.0.1). Going back to my printer, I received the same "Out of Memory" screen as shown above.

I'm not sure, but it might have been the case that my phone swapped access points (and therefore shortly disconnected) while loading the Web Interface.


Can provide gcode and crash dump if needed (not uploading directly as I don't know if it contains sensitive information).

**Comment by mikebdub** [comment]
Just had the same issue for the first time today. I ran numerous duplicate prints from the same .STL yesterday without issue. I started another print locally from the printer itself (same print again) but it did not stick very well so I cancelled it at the printer. While the printer was cooling down I walked away from it to go get some new paper towels to wipe down the bed. About 5 minutes later while the printer was sitting completely idle, the buzzer started going off and the red screen saying out of memory popped up. First time that I can think of that I have had a problem out of this Mini+

Prusa Mini Firmware: 4.4.1+4194
Bootloader: 2.0.2
Additional Upgrades: Filament sensor, ESP-01S WiFi Module, Bondtech Extruder

Printer connected via WiFi. No access to prusalink at the time of error (pc was off).

**Comment by Prusa-Support** [comment]
Thank you all for your feedback. The more we have, the better we are.
We'll keep on collecting relevant information about this quite erratic error.

Michele Moramarco
Prusa Research

**Comment by Levi--G** [comment]
I got the error today with only a small gcode uploaded from prusaslicer after running another print.

Timeline:
-upload and start print 1 from prusaslicer
-print fails with first layer issues
-i stop the print and start it again after cleaning sheet
-printer complains of wrong filament (im printing pctg and loaded petg)
-print finishes ok
-printer cools down and i remove the item
-start new print from prusaslicer
-prusaslicer errors it can't start the print but it was uploaded or smth (sorry i can't remember)
-i find the printer on the start print screen
-i press print
-printer complains about filament again
-malloc error occurs upon pressing ok

this is the most complete i can describe the event, hoping it can help

Happy Printing!

**Comment by Ronin0000** [comment]
Same problem here. Was doing a 16 our print and then failed halfway through when I went to check on it through the prusa link. Also happened to me 3 other times when uploading files.

**Comment by oskrabanek** [comment]
Same issue on firmware version `4.4.1+4194`, bootloader version `2.0.2` and Buddy board version `1.0.8`. The print has been sent using ethernet to USB flash and failed with red screen `Out of memory`.

**Comment by vitorecomp** [comment]
Same issue on firmware version 4.4.1+4194, bootloader version 2.0.2 and Buddy board version 1.0.5. The print has been sent using Wifi to USB flash and failed with red screen Out of memory on the middle of the print.

**Comment by WarrenSchultz** [comment]
Ran into this on the mini on 4.4.1+4194. I had a print running from USB, and opened the web interface to check status, and it killed the print and caused the out of memory message to appear.

**Comment by dwbmb** [comment]
Yeah I am not using Prusa Link to check status anymore, just for uploading tasks. Ruined couplne of prints trying to check progress.
