### ISSUE TITLE
[BUG] filament-runout-sensor not recognized when using Prusalink

### ISSUE THREAD

**Issue by ErGeeBee** [prusa3d/Prusa-Firmware-Buddy#2822]
**Printer type** - Mini+

**Printer firmware version** - [4.4.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
 Prusalink/USB

**Describe the bug**
When using Prusalink either through webbrowser or Prusaslicer physical printer, the filament-runout-sensor does not recognize that filament is not inserted. Also the print just starts even if gcode is made for another printer.

**How to reproduce**
Following steps in attached video

**Expected behavior**
I would hope that printing with Prusalink would give the same warnings on the Mini+ screen as when printing directly on the printer.

**Video**

https://user-images.githubusercontent.com/114698077/206927515-c9babaa6-b431-4931-9bf7-f3f9b5a19ad3.mp4

**Comment by Prusa-Support** [comment]
Same as https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2334, I'm afraid that Prusa Link can't reproduce the printer's typical error messages and warnings at the current stage.

Thanks for reporting. Our developers will work on this.

Michele Moramarco
Prusa Research

**Comment by HaWiWe** [comment]
It could also be that the sensor is disabled in the settings, that was the problem with mine. It resets the settings every reboot though. 😑

**Comment by Prusa-Support** [comment]
Sorry for the late reaction.
Recently the presence of a bug making the filament sensor turn off (under specific circumstances) seems to be confirmed.
Please read more at https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1833#issuecomment-1585040893. 

As previously mentioned, the lack of printer statutes/events notifications through Prusa Link instead is a known limitation at the moment.

Please allow me to close this issue since it partially duplicates other more specific and progressed ones.

Michele Moramarco
Prusa Research
