### ISSUE TITLE
[ENHANCEMENT] PrusaLink Information about the type and weight of the used filament

### ISSUE THREAD

**Issue by eWuPi** [prusa3d/Prusa-Firmware-Buddy#2856]
**Is your suggested improvement related to an existing problem? Please describe.**
  Because I use Home Assistant, it would be useful to be able to read the type of filament and the currently used weight (or length) in order to determine the cost of printing at the HA level.

**Describe the expected functionality**
  Adding functionality to the API about the type of filament and the current weight (or length) in a given printout.
  Dodanie funkcjonalności do API o typie filamentu oraz aktualnej wadze (lub długości) w danym wydruku.

**Comment by Prusa-Support** [comment]
This issue partially relates to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2334 (older) and it is actually implied by issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2878 (newer, more generic).
Even though this issue was opened before the latter, please allow me to close this one as a duplicate because the other one is more generic and is already being watched by our developers.

Michele Moramarco
Prusa Research
