### ISSUE TITLE
[ENHANCEMENT] Allow PrusaLink Printing when printer is on the reprint screen 

### ISSUE THREAD

**Issue by markdesouza** [prusa3d/Prusa-Firmware-Buddy#3028]
Enter what type of printer or upgrade the enhancement applies to.
Prusa Mini+
Prusa Link

**Is your suggested improvement related to an existing problem? Please describe.**
Currently you can only start a print from PrusaLink when the printer is on the home screen, which makes sense. However, this means that if a print has finished and you have cleaned the build plate but forget to click home, you can not start a print remotely.

**Describe the expected functionality**
Treat the post print screen (where the options are Home, Reprint etc) the same as the home screen for the purposes of allowing a print to start via PrusaLink

**Comment by mix579** [comment]
Or better, from any screen ☹️

**Comment by markdesouza** [comment]
Well I can understand blocking if the printer is currently performing an operation ie printing, un/loading filament etc... but a successful print screen where its sitting idle seems a bit much

**Comment by Prusa-Support** [comment]
Thanks for reaching out to us.

This is a known limitation and intentional as stated in the release notes (November 2022).

> *MINI+ must be on the home screen and “print-preview” screen - this is intentional for safety reasons

https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.4.0

This behavior may change or be corrected via new features (e.g. "programmed" statuses via Prusa Connect) in the future.

Michele Moramarco
Prusa Research
