### ISSUE TITLE
[BUG] Bearing jumping when parking on calibrating

### ISSUE THREAD

**Issue by LyxxSK** [prusa3d/Prusa-Firmware-Buddy#3037]
Hi, i update fw to 4.4.1 and i have problem when calibrating my mini+(firt layer calibrating) When i run self test xyz everything is ok. This bug showing only calibrating(first layer calib..)
here is video: 

https://ulozto.sk/file/scL1KPgInVC6/img-0433-mov#!ZGWwBQR2AwV0ZmSzAmWuLmLjBQD4LGMQIz5OIKcQE2WypQH3At==

https://ulozto.sk/file/QyDTQDHd1cBY/img-0429-mov#!ZGV0MGR2ZzH5AwR2ZmuvA2L4MTRmMyyPLmRkGJyAM2EVAzEwMt==

when i downgrade to 4.4.0 everything is ok..

**Comment by Spacekoaster** [comment]
Hello, 

I've got the same exact problem on my Mini+. Firmware 4.4.1.

**Comment by LyxxSK** [comment]
I maybe find bug. When i have inserted my usb 32gb in mini+ bug is here. But when i calibrating first layer without inserted usb . Everything is okey. Problem is inserted usb…

**Comment by LyxxSK** [comment]
.

**Comment by migdard** [comment]
I had the exact same problem some times, but not always. I thought it was one of my belt tension being too high. Have not checked if related to USB key inserted or not, but will try.

**Comment by Prusa-Support** [comment]
I'm sorry, we haven't heard clarifications from you and I'm considering closing this issue as invalid and a possible duplicate.

Michele Moramarco
Prusa Research

**Comment by migdard** [comment]
Agree to close.  The issue actually did not reappear for me, after I went trough mechanical calibration in various ways. Thank you.

**Comment by Prusa-Support** [comment]
Thank you for your feedback.

Michele Moramarco
Prusa Research

**Comment by migdard** [comment]
Hi 

I have had a reoccurrence with the latest alpha firmware, see https://youtu.be/nkIjVXSwUDM 

I had not printed in a while and upgraded to 5.1.0-alpha1 straight away but the problem is totally identical to how it was with 4.4.1.

Basically it happens just before mesh bed levelling, if for some reason the bed is already at one end of the Y axis. Then as we can see it looks like the printer "tries too hard" against what is already max (or min) Y offset.
