### ISSUE TITLE
[BUG] MK4 screen turning off/flashing in the middle of a print

### ISSUE THREAD

**Issue by HaWiWe** [prusa3d/Prusa-Firmware-Buddy#3142]
**Printer type**
MK4

**Printer firmware version** -  [e.g. 3.8.1, 3.8.1-RC1, ...]
5.0.0-alpha3 Firmware for Original Prusa MK4

**SD card or USB/Octoprint**
USB

**Describe the bug**
The screen of my new MK4 often turns off in the middle of prints (but not always), the print will finish but the screen either turns black, partially turns black/white or shows the wrong colours. It's basically all of the behaviour found in this thread: https://forum.prusa3d.com/forum/english-forum-original-prusa-i3-mk4-assembly-and-first-prints-troubleshooting/mk4-screen-goes-blank-after-some-time/

I do use the newest alpha firmware, since this was a proposed fix, so this can't be it. I also checked all the cables and made sure they were seated right. I linked a video of the problem. I'd be happy to get some pointers as to what is really causing the problem.
  
**To Reproduce**
There is no way to reproduce it since it happens at random times.
  
**Expected behavior**
The screen should not turn off/show wrong colours.

**Link to a video of the problem**
https://youtu.be/2D3mrdGKFMA

Posting here again because it was posted in the wrong spot (because the link at https://forum.prusa3d.com/forum/input-shaping/5-0-0-alpha3-firmware-for-original-prusa-mk4/ leads to the wrong place).

Thread in the forum: https://forum.prusa3d.com/forum/english-forum-original-prusa-i3-mk4-assembly-and-first-prints-troubleshooting/mk4-screen-goes-blank-after-some-time/

**Comment by 3Delights** [comment]
**FYI**: I've fixed the link on the forum.

**Comment by HaWiWe** [comment]
>  Regarding the LCD issue, could you try to: 
factory reset of the printer (hard reset)
reconnect the cables again (mainly those on the LCD side itself)
try to clean the connectors with canned air
doublecheck the LCD cable for any kind of damage

Update: I did all of those and the screen went blank again on a longer print.

**Comment by HaWiWe** [comment]
Today, after the print finished, the screen came back with inverted colours. It did that once before but I didn’t draw the connection then.
So it definitely has to do something with EMC.

![IMG_20230722_084024](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/123641715/9f7f52d1-863e-457d-869d-1b739e656fdd)

**Comment by HaWiWe** [comment]
Support thinks it is an xLCD problem and they are exchanging it. If it really is, I am going to close this thread since it is not related to software then. Until proven, I will leave it open.

**Comment by Prusa-Support** [comment]
Thanks for reporting.

Only a negligible percentage of units have been affected by similar problems but our Quality Control returned and inspected quite a number of xLCD panels over the last few months and they almost always diagnosed that the panel was just fine.
So far we could only point out interferences due to loose cables or poorly grounded printers.

Re-seating the connection usually helps but please make sure the printer is **correctly grounded** too.

- Inspect and reseat the goldish flat cables behind the xLCD: there are two of them.
https://help.prusa3d.com/wp-content/uploads/2023/06/1c8b8610bc941ddb7888a2b975adf6ec_painted.jpeg
Their locking mechanism may need to be slid or flipped to release the cable - https://imgur.com/a/3w4ygus.

- Inspect and reseat the whitish ribbon cable on xLCD and xBuddy.
Be careful with its reddish connectors, as they don't necessarily clip in place but need uniform pressure from side to side for a secure connection.
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#437352
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#461085

- Inspect and reseat the PE cable on its three terminals, and make sure they won't wobble or rotate.
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#437352
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#437580
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#438112

- Make sure the PE Faston is firmly stopped in place and doesn't rotate.
https://help.prusa3d.com/guide/6-xlcd-assembly_437030#460575

This said, our developers will dig further into this, trying to understand if anything can be done to reduce the chances of interferences, however, this is a hardware matter, so please allow me to close this issue.

Michele Moramarco
Prusa Research
