### ISSUE TITLE
[BUG] Print time not matching reality

### ISSUE THREAD

**Issue by Jothoreptile** [prusa3d/Prusa-Firmware-Buddy#3151]
Prusa mk4 with latest alpha firmware.

Receive it monday 17/07 (assemble it in the night). Been printing with it since this time (but not 24/24). When a look at the Print time in the odometer I found the values really weird (like 3 day and 15 hours but it have been less than 3 days that I have it). And just after when lauching a 3 hours print the odometer shows a +6h on the print time (see photo just bellow).
![IMG_20230720_201916](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/113062793/5ef2c342-bc89-41ec-8804-ab952e5364d4)
![IMG_20230720_234054](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/113062793/3c86abce-4340-445c-aa90-ee8509ed5552)

**Comment by nvtkaszpir** [comment]
only 3 days? 
here's better:

![chrome_i8QTTm5eL4](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1480252/f3183415-842a-4144-af24-462158529202)

that's about 136 years.
:D

**Comment by t-makaro** [comment]
I noticed this yesterday on my Mk4 with the 5.0.0 stable release firmware. 7 hours of printing (2 prints) and the time increased by 21 hrs.

**Comment by amagreenhow** [comment]
I also have this problem on my MK4 with the 5.1.2 stable release firmware. The ODOMETER Print Time is currently increasing by about twice the actual print time for each print.
Today the ODOMETER Print Time went from 8 days 21 hours to 9 days 0 hours after printing a just over 1 hour 27 minute print and again after reprinting the same print it went from 9 days 0 hours to 9 days 3 hours

**Comment by GlowingEye** [comment]
This issue still persists on my MK4 running 5.1.3 (stable release). The print time in the statistics is roughly doubled. I reset the printer twice, even reflashed the firmware and the issue is still there. In my example, the print took 10 min and 3 s while the statistics increased from 0 min to 25 min and 16 s (after reset, thereby zero before the print).

![IMG_3687](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/73438231/be18c5aa-f2eb-4c8b-a47a-edf40cefa768)
![IMG_3688](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/73438231/6e38cc50-2e50-4762-8a45-68965f8b7d9c)

**Comment by danopernis** [comment]
Although this issue is older than duplicate https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3220 I am closing this one because the title and description of the other one better _matches reality_.
