### ISSUE TITLE
[BUG] "Print" screen causes stuck UI and unresponsive web interface

### ISSUE THREAD

**Issue by neuron-whisperer** [prusa3d/Prusa-Firmware-Buddy#3159]
**Printer type** - MK4 built from kit

**Printer firmware version** - 4.7.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** - USB drive

**Describe the bug**
"Print" screen causes stuck UI and unresponsive web interface

The MK4 often gets stuck on the "Print" screen. The display actively scrolls the filename, and rotating the dial causes it to change the focus between the two displayed options ("Print" and "Return," I think). However, the UI does not respond to selecting either option, and the printer remains on this screen indefinitely (without printing anything or changing the bed or extruder temperature). Escaping this screen requires either hitting the Reset button or power-cycling the printer. 

While stuck on this screen, the printer becomes unresponsive to the web interface - any and all page requests result in a timeout.

This issue very often occurs after uploading a file via the web interface: the printer loads it and switches to the "Print" screen for confirmation, but then gets stuck there.

**How to reproduce**

Simply upload a model, any model, via the web interface. About 30% of the time, the printer enters the "Print" screen and gets stuck there.

**Expected behavior**

While displaying the "Print" screen, the UI should be responsive to either the "Print" option or the "Return" option, and the web interface should be responsive and available.

**G-code**

The model is not the issue - this bug has occurred with at least 10 different models, all sliced by the most recent version of Prusa Slicer.

**Crash dump file** - None

**Video** - None

**Comment by Phardbean** [comment]
Having the same issue in alpha 4  ... and sometimes when I try to start a new print it freezes.

**Comment by Prusa-Support** [comment]
Thanks for reporting.

This issue is hardly reproducible so we can't confirm a bug but there could be various reasons for similar erratic glitches.

The next firmware 5.1.0 with "g-code streaming" should drastically change the way the print files are transferred via Prusa Link and handled by the printer's firmware and will probably address this occurrence too.

You can already try the alpha version [5.1.0-alpha2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.1.0-alpha2) but please keep in mind this firmware may not be totally stable - only recommended to advanced users who can take the risk.

Michele Moramarco
Prusa Research
