### ISSUE TITLE
[BUG] XL firmware upgrade didn't upload bootloader until factory reset

### ISSUE THREAD

**Issue by RichiH** [prusa3d/Prusa-Firmware-Buddy#3168]
**Printer type** - [XL]

**Printer firmware version** - [4.7.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [n/a]

**USB drive or USB/Octoprint** - [USB]

**Describe the bug**
While upgrading my firmware as per https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3167 I upgraded from unknown to 4.7.0. After the upgrade, the bootloader was at 2.0.7 over several restarts.
I had to factory reset due to an unrelated issue, and after I factory reset it booted with 2.0.8. I ~obviously can't reproduce this, but I am 100% certain about the observed behavior, I watched the screen from start, over factory reset, to restart very intensely and was .

**How to reproduce**
See above, I can't, sorry.

CC @pstrobl96

**Comment by Prusa-Support** [comment]
Thanks again for reporting.

This issue is a continuation of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3168 and is not specific enough to be considered as a separate case, so let me link it to the previous issue and close it.

Same as https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3168, we need to be able to reproduce the problem to work on it but we are positive that the problem won't persist on future firmware releases - probably not if you upgrade firmware release after firmware release from now on. If that will be the case though, please post further similar observations on the thread of issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3167.

On a side note, while firmware upgrading normally wouldn't require a factory reset, not all obsolete data stored in EEPROM would necessarily be overwritten, and old data may occasionally create a conflict. In case of glitches that are consequent to a firmware installation, please consider giving the [factory reset](https://help.prusa3d.com/article/factory-reset-mk4-xl_421206) a go, as that would most likely solve the problem.

Michele Moramarco
Prusa Research
