### ISSUE TITLE
[BUG] MK4 Mid-print BSOD HARDFAULT 5.0.0-RC

### ISSUE THREAD

**Issue by flyingkillerspacepixies** [prusa3d/Prusa-Firmware-Buddy#3214]
Some of the issues seem kind of similar but seem different enough to be a potentially different issue.

**Printer type** - MK4

**Printer firmware version** - v5.0.0-RC

**Original or Custom firmware** - Original

**Optional upgrades** - Nextruder V6 adapter + Hardened Steel Nozzle. Custom G10 print sheet

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug**
  The printer bluescreens midway through a print sometimes.
  I printed several prints on the mk4 alpha versions up to and including 5.0.0-alpha3 and I never had this issues happen on any of those versions. I had it happen twice now in the v5.0.0-RC since updating it yesterday

**How to reproduce**
  I'm really not sure at the moment, but if I had to guess, it has something to do with leaving prusalink open the whole time during a print. Both times that this happened I had prusalink open from the start of the print.
  I'll try to grab a relevant pcap if I have time.

also just f.y.i. I sanitized some irrelevant information I did not want to share (replaced some string with other strings) out of the dump file.
attached is a dump file, a gcode file where a crash occurred, and two pictures of the screen at the time of the crashes

[mk4_dump_sanitized.bin.gz](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12403575/mk4_dump_sanitized.bin.gz)
[white_K2_Clip_hardened_0.4n_0.2mm_PLA_MK4IS_20m.gcode.gz](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12403579/white_K2_Clip_hardened_0.4n_0.2mm_PLA_MK4IS_20m.gcode.gz)
![mk4_crash_1](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/137958960/57a75c3f-fb47-4ca0-b36b-0060f5bfc56e)
![mk4_crash_2](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/137958960/1a454f07-f070-480e-85f0-4c5ad128d9c0)

**Comment by Tadaruwa** [comment]
**Printer type** - MK4

**Printer firmware version** - 5.0.0

**Original or Custom firmware** - Original

**Optional upgrades** None

**USB drive or USB/Octoprint**
USB drive

**Describe the bug**
The printer bluescreens midway through a print sometimes.

**How to reproduce**
its seems random. Most prints work for me.
I have no LAN connected. WLAN has a valid config(SSID/password) but no connectivity. 2.4GHz is disabled for the WLAN. only 5GHz is enabled.

**Expected behavior**
no crash

**G-code**
[gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12707932/gcode.zip)

**Crash dump file**
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12707931/dump_buddy.zip)

**Video**
![IMG_20230924_073537](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/145891755/d0e34130-5b9f-403e-b5fa-691cd939f87c)
