### ISSUE TITLE
[BUG] Alpha2 MINI+ BSOD error heap.cpp:37

### ISSUE THREAD

**Issue by osvch** [prusa3d/Prusa-Firmware-Buddy#3375]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - 5.1.0-alpha2

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
 USB flash drive

**Describe the bug**
 I sliced benchy with PrusaSlicer 5.1.0-alpha2, copied to USB drive. After selecting model and hitting print I receive fault as attached heap.cpp:37
Attached zip is buddy dump and binnary gcode.

**How to reproduce**
Slice new model, export to usb drive, select print- fault occures

**Expected behavior**

**G-code**
in ZIP file

**Crash dump file**
in ZIP file

**Video**
  Please attach a video. It usually helps to solve the problem.
![20231021_122914](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/139809314/a470213b-e9b7-48a0-925d-7853412ac8da)
[dump_buddy_gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13060617/dump_buddy_gcode.zip)

**Comment by osvch** [comment]
UPDATE:
I've done hard reset of printer and issue no more present.

**Comment by abstractFlo** [comment]
What do you mean with hard reset? I have this error after start a new print if one was done before

**Comment by Pitel** [comment]
Same crash, but when sendig from Slicer over Wifi.

[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13064188/dump_buddy.zip)

**Comment by osvch** [comment]
> What do you mean with hard reset? I have this error after start a new print if one was done before

Factory reset -> Hard reset - require copying FW file on USB stick.

**Comment by Jerzeek** [comment]
Same problem here.

**Comment by Pitel** [comment]
I've now successfully printed 2 small models without any crash! The key was to **disable binary gcode** in slicer.

**Comment by samdurnxn** [comment]
No problem at all for me with binary gcode files but when I upload a file via prusaConnect wich have the same name as an existing file. The file is correctly overwrite on USB drive but when the printer want to start printing same BSOD.

I restart the printer, only change filename and everything is ok

**Comment by chrishilbert** [comment]
Happens to me as well.  All my Minis will have this error at some point and require a restart.  It can happen from a wifi send OR from a selection on the screen.

I am trying to determine the cause.  It usually happens when I do back-to-back prints - the machine is still warm and cooling down.  I will do more tests to confirm.

**Comment by matejus** [comment]
Identical exception ... after i loaded the file over PrusaConnect. It was the very first print over connect. It succeeded when I start the print of the same file again over connect. the same procedure with different file also finished without BSOD.

**Comment by danopernis** [comment]
This is caused by dynamic memory allocation in heatshrink decompression library used in binary gcode. It is triggered anytime when the memory is fragmented and printer needs to open binary gcode. It is most prominent on MINI due to its smaller RAM, but may theoretically happen on any other printer. We are aware of the issue and tracking it internally as BFW-5023

The workaround is to disable binary gcode as suggested by @Pitel

**Comment by Pitel** [comment]
I've kept using binary gcode, and actually hasn't seen any crash for a long time.
