### ISSUE TITLE
[BUG] MBL failure and nozzle crashing into heatbed

### ISSUE THREAD

**Issue by lazRo88** [prusa3d/Prusa-Firmware-Buddy#3494]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - [5.1.0-beta]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
PrusaConnect via WifI Module

**Describe the bug**
When starting the print the mesh bed leveling will cause a probe failure in the first run and the nozzle runs into the heatbed. After this I can press restart and in most of the cases the probing will work but sometimes it needs 2-3 attempts to be successful.

**How to reproduce**
  It will show in 90% of the started prints but not when using the first layer calibration.

**Expected behavior**
  A clear MBL in the first run

**G-code**

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the 

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by tsaro** [comment]
I had a very similar issue where my printer would reliably fail at the 6th point during the MBL stage, only started happening on the 5.x firmware, turned out my XZ-axis was way out of spec, fixing that and now the MBL completes without issue https://forum.prusa3d.com/forum/input-shaper-mini/auto-bed-levelling-failing-on-6th-test-point/#post-686062
