### ISSUE TITLE
[BUG] CRASH DUMP FILE contain unencrypted password to the WIFI.

### ISSUE THREAD

**Issue by mixer3d** [prusa3d/Prusa-Firmware-Buddy#3528]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]
MINI+

**Printer firmware version** - [e.g. 4.0.5, ...]
5.1.0

**Original or Custom firmware** - [Original/Custom]
Original

**Optional upgrades** - [e.g. Filament Runout Sensor]
Filament Runout Sensor

**USB drive or USB/Octoprint**
USB

**Describe the bug**
I had other issue with printer BSOD, already reported in another bug report, and out of curiosity i checked what is included in the blod generated by the board... and i found unencrypted password to the WiFi network i used to connect printing devices. 

**How to reproduce**
Using WIFI as an interface, when you have BSOD, and decide to generate crash report it contains WiFi password with plain text in the dump "bin" file it contains the plain text password. 

**Expected behavior**
 I do not expect to see any password there. 

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
exactly this is the problem with that file

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by mixer3d** [comment]
i just checked and the test version before (alpha1 or 2, do not remember whan i generated the file) was also including password inside the file...

**Comment by rcmaniac25** [comment]
Can confirm, my recent crash dump had the credentials in it in plane text and I've since removed the dumps from my tickets.

**Comment by rcmaniac25** [comment]
This also appears in the dumps from 5.1.0 alpha2

**Comment by mixer3d** [comment]
yes, the API key used to authenticate to the printer is also present as a plain text string...

**Comment by b-man** [comment]
I've taken a look at how the firmware stores credentials for WiFi and PrusiaConnect, and it seems that the firmware stores this data within a [journal](https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/src/persistent_stores/journal) on an eeprom. It seems that the [full contents of the journal gets read out](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/src/persistent_stores/store_instances/config_store/store_instance.cpp#L51) on [every boot](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/src/buddy/main.cpp#L700) and the values are stored in a config_store singleton (so everything is held in RAM during runtime).

So it seems that one way this security hole could be mitigated would be to tag this data in the journal such that its not directly stored in the config_store singleton and is only read from the journal on the eeprom as its needed (and the values zeroed out of RAM upon successful authentication, avoiding leaked confidential data in crash dumps).

**Comment by rcmaniac25** [comment]
I just noticed there's a new firmware (5.1.2) and the release notes state
```
Sending crash dumps to Tech support

In the event of a system crash, a memory dump is created. You can download this crash dump on a USB drive and send it to Prusa Research tech support for further investigation. The file may contain sensitive unencrypted information, therefore we strongly recommend sending the file directly to reports@prusa3d.com and avoiding uploading the file to any public cloud storage or sharing it on social networks.
```

So I take it they've seen this ticket.

**Comment by Prusa-Support** [comment]
Yes, the dump files may contain sensitive information. The included data may not be closely personal, but it is especially important to protect dumps now, since the integration of the internet connection, including basic network information.

_We implemented a safety message on the printer' screen, not to share dumps publicly._
Possibly please refrain from sharing dump files publicly but email them to [reports@prusa3d.com](mailto:reports@prusa3d.com), if directly requested by our staff.

I hope this clarifies.

Michele Moramarco
Prusa Research

**Comment by rcmaniac25** [comment]
It would still be nice to have either the firmware or some tool (maybe PrusaSlicer?) that would strip the data out. But if email will get a ticket checked, then it may not matter much.

**Comment by mixer3d** [comment]
@Prusa-Support thank you for update.

**Comment by Prusa-Support** [comment]
Yes, in response to the email you will get a reference number, even though it is mainly used for reference rather than as a ticket.

If the failure is recurrent and prevents the regular use of the printer, besides submitting dump files to reports@prusa3d.com for the developers, you can carry a regular ticket with Customer Support until a satisfying solution is found for your individual case. 

This issue includes useful informative material but, if you got all the answers you needed, I suggest closing it as it will remain discoverable anyway.

Michele Moramarco
Prusa Research
