### ISSUE TITLE
[QUESTION] grey buttons in new firmware 5.1.2

### ISSUE THREAD

**Issue by LeanderJDev** [prusa3d/Prusa-Firmware-Buddy#3677]
I'm sorry if this comes out as petty, but I upgraded from firmware version 4.4.1 to 5.1.2 and was immediately shocked by the background color of the buttons. I really do not like this grey. Why was the background color changed? I mean it's not even an accessibility issue, the new color scheme rather makes the contrast lower and thus the icons harder to read

**Comment by danopernis** [comment]
As a firmware developer, I am not UX expert and I don't know why it was changed. I am sorry but I can't tell you more about this change. It will certainly not be reverted on MINI because there is a tendency to unify user interface between different printers. Making it configurable is also not likely to happen, can't justify the required IROM for such a petty change.
