### ISSUE TITLE
[BUG] MMU2S to MMU3 upgrade: Selector cannot home #04115

### ISSUE THREAD

**Issue by calipsoii** [prusa3d/Prusa-Firmware-Buddy#3841]
**Printer type** - MK3.5
**Printer firmware version** - 5.2.1

**MMU upgrade** - MMU2S->MMU3 upgrade
**MMU upgrade firmware version** - 3.0.2+878

**SD card or USB/Octoprint**
USB/Octoprint

**Describe the bug**
After upgrading my MMU2S to an MMU3, the selector cannot home if it is parked >50% of the way to the right. It displays error "Selector cannot home #04115". It WILL home if manually moved <50% of the way to the right. There are at least two other customers who followed the same upgrade path as me and are having the same issue, their comments are at the bottom of this article:
https://help.prusa3d.com/article/selector-cannot-home-04115-mmu_396152

**To Reproduce**
With no filament loaded, place the selector (either automatically or manually) 50%+ of the way to the right towards the selector motor. Take any action that triggers a selector home, such as hitting the Restart button on the front of your MK3.5. Your printer will start up successfully, then the MMU3 will attempt to home. The idler will successfully roll on the X axis. The selector will attempt to home, and if it's any closer than 50% of the way towards the selector motor, it will bump 3x against the housing and display error "Selector cannot home #04115".

**Expected behavior**
My expectation is that the selector will be able to home itself no matter where it is parked. This was the behavior on my MMU2S.

**Video**

Here is a video of my MK3.5 sitting idle with the selector placed almost all the way to the right. I reboot the machine and the MMU3 fails to home:
https://calipsoii-1d4279c752674f6b5f9b-endpoint.azureedge.net/blobcalipsoii3eb2982b2a/wp-content/uploads/2024/03/mmu3-selector-cannot-home-reboot.mp4

Here is a video of the selector manually moved 66% of the way across its bars towards the selector motor and again failing to home:
https://calipsoii-1d4279c752674f6b5f9b-endpoint.azureedge.net/blobcalipsoii3eb2982b2a/wp-content/uploads/2024/03/mmu3-selector-2thirds-right-1.mp4

Here is a video of the selector moved 50% of the way across it's bars (away from the selector motor) and succeeding. The same will work anywhere from 0%-50% of the way across the bars (away from the selector motor).
https://calipsoii-1d4279c752674f6b5f9b-endpoint.azureedge.net/blobcalipsoii3eb2982b2a/wp-content/uploads/2024/03/mmu3-selector-CAN-home-middle.mp4

**Comment by calipsoii** [comment]
**Troubleshooting update**: I've managed to seemingly resolve this issue (only been testing for 1 hour now but looks promising) by loosening the 3 machine screws holding the selector motor to the MMU3 body. I loosened each of these 3 machine screws approx. 1/2 a turn. The selector motor now jiggles very slightly when I shake it - it's no longer held securely to the frame. But I can get the selector to home in any location with 100% success.

My theory is that tightening the selector motor to the MMU body positions the long silver leadscrew off-center. Then, as you move to the selector carriage to the right, the leadscrew is being pushed up on the left side until it contacts the MMU body and the friction increases. Alternatively (and perhaps more likely): the leadscrew is being pushed to an odd angle within the trapezoid nut on the selector and friction is becoming far too high.

I believe this because when the 3 machine screws are fully tightened, the leadscrew is extremely difficult to turn when the selector is close to the motor. But the second you loosen the selector motor screws, the leadscrew becomes quite easy to turn with your fingers, even when the selector is all the way to the right. There seems to be a LOT of friction introduced when the selector motor is tightened to the MMU body, and the stepper motor seems to be having troubles overcoming it and reports that it cannot move.

I don't see any obviously visible difference between the screws being tight:
![IMG_0173](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50472329/ce92b1ba-16a2-4de4-a293-3638ab87b660)

And the screws being loose:
![IMG_0174](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50472329/7f183a17-8949-4025-93bf-dcd9505a38e7)

But I can definitely feel with my fingers how much harder the motor leadscrew becomes to turn when fully tightened.

For now I'm going to leave all 3 loose, but this is a poor solution and the entire assembly makes a rattling noise in operation. Not only that, the movement of the selector stepper motor will eventually loosen the screws until they fall out. Can you please attempt to reproduce with an MMU2S->MMU3 upgrade kit and let me know if you see the same behaviour?

**Comment by nicebam** [comment]
I am using MMU2S->MMU3 on MK4.
I too am experiencing the "Selector cannot home" issue.
I tried both the above solutions and "Selector cannot home #04115", but initialization failed.
Of course, the operation of MMU2S in MK3S+ was perfect.
It causes problems in MMU3.

**Comment by calipsoii** [comment]
Issue is not stale, it is ongoing. Currently mitigated by loosening (and sometimes tightening) selector motor screws, but it remains an issue.

**Comment by Prusa-Support** [comment]
Thanks for reporting however, as far as I can tell from my experience, and again after consulting the developers, this problem is only reproducible in the case of relevant assembly/hardware inconsistencies so this has little to do with this repository (**not a firmware problem**).

> Troubleshooting update: I've managed to seemingly resolve this issue [...] by loosening the 3 machine screws holding the selector motor to the MMU3 body. [...]

This is actually a good piece of troubleshooting.
The lead screw may not be perfectly straight and having the selector slightly loose may give the selector a little extra degree of freedom to work with. However, _this is more likely the case of slightly deformed printed parts under rather tight bolts_.

All in all, there should be no gaps between the Selector motor and the printed part, and the selector motor itself shouldn't shake in place, but you should definitely _avoid_ force while tightening screws against plastic parts. In fact, nothing will prevent the plastic from deforming under an even slightly too-tight bolt.

Normally no special attention would be required but gentle tightening. However, you may want to follow these steps to be on the safe side.
- Tightening the bolts while the [selector motor lies vertically](https://cdn.help.prusa3d.com/wp-content/uploads/2023/03/98b43425963a57eb_painted.jpeg) can avoid torque on the motor, reducing chances of skewed screws.
- For higher sensitivity, you may want to hold the L-shaped hex key with the tip of two fingers only, holding it from the short arm (short arm to avoid leverage).
- When you feel increasing friction, visually check if there is a gap between the head of the bolt and the printed part.
  - If there is a gap but you feel significant friction as the screw gets threaded in the plastic, you may want to undo the screw by several turns and repeat. This should help the screw to find its way into the plastic part.
  - If there is no gap, then you are good but you may want to ensure the parts hold firmly in place (no wobbling).
- Once satisfied, you can give it a final 45° (or less) tightening nudge. 

You can follow the same procedure on pretty much all bolts tightened onto plastic parts, [including on the trapezoidal nut](https://cdn.help.prusa3d.com/wp-content/uploads/2023/03/c7ecbd3c0033bb34_painted-1536x1152.jpeg).

This is mostly about the selector motor and general assembly however, of course, there may be additional troubleshooting steps to rule out other more or less severe hardware concerns so, if the problem is recurrent, please reach out to our [Customer Support](https://help.prusa3d.com/article/customer-support_2287) for more help.

I suggest closing this issue as not firmware-related.

Michele Moramarco
Prusa Research

**Comment by calipsoii** [comment]
In that case I haven't much more to add other than that myself and others immediately encountered this issue when following the MMU2S->MMU3 upgrade path. I see no complaints about this problem from people who purchased a new MMU3. So I still have my suspicions that there is a difference between the final MMU product depending on whether you upgraded or purchased new. But you're correct - it's not firmware (though there's no hardware repo where it _would_ fit under) so the issue can be closed. Thanks for your suggestions.
