### ISSUE TITLE
USB maxium size and xBuddy

### ISSUE THREAD

**Issue by OopAck** [prusa3d/Prusa-Firmware-Buddy#3974]
I bought a small footprint USB Scandisk 512GB and worked for a couple of days and now it causing a BoSD on the xBuddy.
I formatted the USB using rufus 3.3 at FAT32 and still BoSD.
Put the original PRUSA USB and BoSD stopped

Would like a small footprint USB so the chances of hitting it and causing damage to xLCD or USB.

Question:
Is there a size limitation with firmware 6.0.0 and xLCD?
What is the largest USB key size tested with 6.0.0?
Recommended steps to format / or make an 3rd party USB compatible with xLDC / 6.0.0?

**Comment by murk-sy** [comment]
https://help.prusa3d.com/article/sd-cards-and-usb-drives_112291
The help page is a little bit confusing since it doesn't just explicitly say "use FAT32".

It does say however exFAT is not supported, and that's correct: it's disabled in Buddy firmware https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/f69118723a41ecef761be9df96205b9cf4571331/include/buddy/ffconf.h#L211

So max you can use is 32GB FAT32, and make sure to use MBR when formatting it (not available in the default windows formatter, but should be the default on USB drives that size).
