### ISSUE TITLE
[BUG] MK3.5 stealth mode is louder than MK3S+ even in compatibility mode

### ISSUE THREAD

**Issue by adrienafl** [prusa3d/Prusa-Firmware-Buddy#3989]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3.5

**Printer firmware version** - 6.0.0

**Original or Custom firmware** - Original

**Optional upgrades** - Revo nozzle

**USB drive or USB/Octoprint**
USB Drive

**Describe the bug**
 I can't find a way to print with the same noise level I had with me MK3S+. I tried stealth mode when printing with MK3.5 input shaper profile and it's very loud. Then I also tried to print using my old MK3S+ slicing profile. The printer asked if I wanted to print in compatibility mode, I said yes. However, the stealth mode settings doesn't change anything

I've read a few other issues of users complaining about the same thing. I guess that it will be hard to be quieter when printing with input shaper + the old motors. However, I don't see why it wouldn't be possible to at least support old stealth mode when printing in MK3S+ compatibility mode.

Thanks !

**Comment by E3DYAC** [comment]
Same here, I have both (mk3s+ and 3.5) when I saw the update I thought  it's solved, but nothing has change. Even with the stealth mode activated the print time was the same as normal mode but supposed to be more extended (checked with Prusa Connect). In addition since the first pre-release of Mini+ IS this was silent per se without the stealth mode update.
