### ISSUE TITLE
[BUG] Changing filament on Prusa XL 5TH on Tool4 also preheats Tool1

### ISSUE THREAD

**Issue by Investegate** [prusa3d/Prusa-Firmware-Buddy#4107]
### Printer model

Prusa XL 5TH

### Firmware version

6.0.4

### Printing from...

USB

### Describe the bug

For example, if I change the filament on tool 4, tool 1 is always heated to 170c even though I haven't changed anything... I then have to deactivate it manually.

**Comment by MalikDrako** [comment]
I'm seeing this too, but I think it's a bit more general than this.
After changing/loading/unloading the filament on any tool other than T1, T1 is set to the standby temperature (170C), while the active tool remains at the change temperature.

Expected behavior: the active tool is set to the standby temperature, all other tools remain unchanged

**Comment by morphias2004** [comment]
This has already been raised in #3552 

Please add comments and upvotes there.

**Comment by morphias2004** [comment]
This absolutely can be reproduced. Why is this not planned to be fixed? It's a pretty simple code change to NOT turn on E1 when performing loads/unloads on other tool heads.
