### ISSUE TITLE
Printer setting "SOLUBLE INTERFACE" kills the print by standby temperature of 70 degree, on multi-head printers

### ISSUE THREAD

**Issue by ufgum** [prusa3d/Prusa-Firmware-Buddy#4156]
### Printer model

XL 5 head

### Firmware version

6.1.2

### Printing from...

prusa connect

### Describe the bug

With "SOLUBLE INTERFACE" the BOVH tool has sometimes a long break, before get used again. With the standby temperature of 70°C the BOVH cloggs the nozzle, because it gets really hard.
If I stand beside the print and switch the temperature by hand to off after each layer, the print will go like expected.

Whipe tower is necessary, so the user should be advised in prusaSlicer, within this profile.

### How to reproduce

Jut use "SOLUBLE INTERFACE" and BOVH

### Expected behavior

the nozzle should go to off, better with fast cooling fan.

**Comment by murk-sy** [comment]
I think this is more of a slicer issue, since the firmware doesn't really know if it'll be using the tool again in 3 minutes or in 3 hours. There is some lookahead but I'm not sure how far, especially in regards to getting hotends up to temp quickly.

Regardless, you should just try setting the filament's **Idle temperature** to 0. It might slow down the print somewhat due to re-heating cycles, but it will drop the temperature to ambient without any intervention.
