### ISSUE TITLE
[ENHANCEMENT] XL Bed Leveling Print area only

### ISSUE THREAD

**Issue by Reesesben** [prusa3d/Prusa-Firmware-Buddy#4252]
### Printer model

XL Multitool

### Describe the enhancement

In its current state the XL feels the need to level the entire build plate if you have 2 objects in opposite corners (Multi material print in back left corner, no sparse layers purge tower in other corner to avoid collision) This takes a considerable amount more time than just leveling the 2 areas actually being printed on. 

### Expected functionality

Ideally the printer would only level the spots with objects and not the in-between areas so do a 4 x 4 on the 2 objects mentioned above instead of 145 points for the whole bed. it should as well only heat the zones with object in or near them instead of the whole bed in the mentioned scenario
![exampleHeatZone](https://github.com/user-attachments/assets/00a1a5fa-f214-423b-9c03-4eced234a229)
![exampleBL](https://github.com/user-attachments/assets/1cca8e7f-24b8-4589-8361-5225b7f43cb4)
![example](https://github.com/user-attachments/assets/0f359767-72ca-4da1-8333-e04204c64bf4)

**Comment by CZDanol** [comment]
Hello,
the printer already is only heating up bedlets that have things or them, however there is intentionally some gradient to prevent the bed itself from warping.

Localized bed leveling would be nice, but the gain for implementing it is not enough to justify the implementation expenses for us, sorry.

Over all, I don't know of a practical reason you'd want your objects this far away, you ideally want them next to each other, not only because of less heating and faster MBL, but also shorter travel times and thus faster print.
