### ISSUE TITLE
[ENHANCEMENT]<Bring back sound type from 4.0.5>

### ISSUE THREAD

**Issue by Hl2run** [prusa3d/Prusa-Firmware-Buddy#603]
[MINI]

The frequency of the old sound when the printer turned on was much much nicer on 4.0.5. The new sound in 4.1 RC1 has a weird frequency. It sounds like some cheap Chinese device. The previous sound was much [more pleasant](http://webstaff.itn.liu.se/~nikro27/tnm103-2019/papers/Analysis%20of%20car%20door%20closing%20sound%20quality.pdf).

Thanks a bunch.

**Comment by x10102** [comment]
I second this. Just updated and it sounds really like some cheap chinese soldering station or something :D

**Comment by Dronitoni** [comment]
same here, the previous sound was much better.
Even if I set it to "silent" mode it makes some noise.

The Mini works in gerneral very silent, that was one argument for me to buy a Mini..
Why adding additional noise to that machine?

**Comment by 4nthonylin** [comment]
@Chleba was this done in #644 ?

**Comment by BerenV** [comment]
I wholeheartedly agree. I can't stand the awful new noises for user interaction. The old ones were so much nicer and felt more clean and professional. Please at least add a mode to switch back to the old ones. It's bad enough that I might even have to downgrade since there isn't anything really useful like Wifi yet 😬 

Thanks!

**Comment by Dronitoni** [comment]
my temporary solution is to put a piece of tape on the buzzer. 
This will at least reduce the noise level a little. 
The buzzer is easy to reach on the back of the control unit.

**Comment by Hl2run** [comment]
Unfortunately the sound is sounding bad in the final 4.1.0 release :(

**Comment by jkavalik** [comment]
@Dronitoni you can switch to silent in settings

**Comment by Dronitoni** [comment]
@jkavalik 
I use the 4.1.0 RC1 at the moment.
There is a "silent" setting but it doesn't really switch to silence.

I have not tried the final release yet. Hopefully it is getting better.

**Comment by jkavalik** [comment]
@Dronitoni well, the sounds seem the same to me, but the "silent" option works for me at least :)

**Comment by BerenV** [comment]
Well my “fix” has been to just downgrade to 4.0.5 😂 I hope the sound gets changed back to the old one though in a future update, or I might have to compile and flash my own modified version 😬

**Comment by Dronitoni** [comment]
@BerenV 
4.0.5 could be a solution for the noise, but will bring back the problems with the USB-Stick detection.

**Comment by BerenV** [comment]
@Dronitoni I’m using OctoPrint so I haven’t had any issues with the USB drive ;-)

**Comment by BerenV** [comment]
Well, 4.2.0 has been pretty good and I appreciate that they added a volume adjustment (although even the lowest setting is still pretty loud). However, the sound is still the same cheap sounding chirp and I have mine set to silent because I couldn't stand it. Sigh...
I wish there was an option to go back to the old subtle but quality sounds for knob rotation and press.

**Comment by JohnnyDeer** [comment]
The sounds have already been improved, I close this issue as solved.
