### ISSUE TITLE
[FEATURE REQUEST]Signed firmware for Bondtech modifications

### ISSUE THREAD

**Issue by ogland** [prusa3d/Prusa-Firmware-Buddy#767]
Josef recently wrote this: "Recently when concern was raised about the appendix and firmwares for modded printers I offered to provide signed firmwares for well tested and safe modifications."

So now I'd like to cash in on this. Since the buddy firmware right after release of the Bondtech extruder and heatbreak removed the possibility to save esteps (and PID values?) this modification is somewhat crippled. As it is the most tested and safe modification that requires signed firmware, it should exist.

So a custom SIGNED firmware with esteps 415 (1/16 microsteps) is hereby requested.

As a sidenote I'd also like the heatsink cooling fan speed to not be limited, which it seems to be right now. Please at least unlock a secret menu where we can set it to full speed.

**Comment by lennertvdkort** [comment]
Couldn't agree more! 
Yes i know you can modify the Gcode. But the filament change is also affected by the esteps.

**Comment by enganear** [comment]
Yes, please. The Bondtech upgrade unlocks a lot of functionality for the Mini. Please release a signed firmware for it.

**Comment by mobileagellc** [comment]
Yes, please!

**Comment by bhbloom** [comment]
Yes please

**Comment by LC3DPS** [comment]
Pretty please! 🙏 Thanks in advance Prusa

**Comment by andrej-petrovic** [comment]
yes please !

**Comment by andresfjs** [comment]
Yessss please.

**Comment by philippbeckmann** [comment]
An even better solution would be to support advanced settings via a new dedicated M-code or the GUI.

**Comment by darkspector** [comment]
+1

**Comment by derenma** [comment]
I _think_ I have seen a PID value save setting in the recent commits, and that is _probably_ going to hit in 4.3.0. _Maybe._ Absolutely don't quote me on that.

I totally agree with the Bondtech upgrade. The flexibility, strength and reliability is absolutely amazing. The stock extruder is perfectly fine, but it cannot handle filament that exceeds +/-0.03mm'ish. When doing draft prints, print quality absolutely does not matter and would rather burn through my awful spools in that regard. Tension adjustment of the stock extruder is, eh, not very good, but it works.

In Prusa's defense, EStep adjustment is a dangerous feature for new printer owners due to the abundance of bad information on the internet. Also, there should be no obligation for Prusa to compensate for out-of-spec filament. This is a company that deals in quality and precision, so why should they have to think about garbage filament?

**Comment by BzuciakCZ** [comment]
+1 for it

No need of official Bondtech support, but return of 
M500 for ESTEPS would be great pain killer for Bondtech upgrade users.
Not to mention, lot of those users choose that upgrade as a last effort dealing with notorious heatcreep problems due to factory hotend assembly issues. 

Future collaboration with Bondtech on future development of MINI would be beneficial for both parties and mostly for customers themselves.

I like my MINI, it was a good printer (after pushing default heatbreak into heatsing) and is great printer after Bondtech upgrade.

**Comment by ogland** [comment]
The only (official) reason Prusa removed M500 was that they were having issues with eeprom not working properly. It wasn't due to some UX ease thing. Esteps can be altered anyway. And even if M500 worked, you could still restore factory settings if some noob messed it up.

The mini doesn't have an e3d hotend unfortunately. It would be great if the stock heatbreak would work as good as e3d heatbreak.

**Comment by JohnnyDeer** [comment]
Hi @ogland, thank you for suggestion. We are considering a solution to this issue.

**Comment by cnEUL** [comment]
Any way, it would be very useful to have m500 support again. Please make savings to eeprom possible again. I had much problems with the original extruder and now i am using Bondtech. It works great. So also i would prefer to support such hacks.
But any way it would be also a good idea to heve better extruder / heatbreak from factory.
I love the mini, it is simple to use, small und fast. Also the GUI is very usefull. Come on...

**Comment by josefprusa** [comment]
Hello everyone. That offer was in respect to the Bear project which is community project. With commercial products there will be some different rules. We will not sign anything which is not thoroughly tested in house for every release, which adds costs. This is all in the making but we will require the producer to have similar customer support to ours with some SLA in order to do it and some other things. 

Regardless the esteps and this issue, we will make similar hidden menu for the new platform as we are doing for the 8bit, which will solve this request.

**Comment by ogland** [comment]
@josefprusa Fantastic! That sounds completely reasonable and very understandable. That reply is 11/10.

**Comment by BzuciakCZ** [comment]
@josefprusa Understood, this is a good solution. Does it mean M500 will be still limited on Mini? (I need it currently only for ESTEPS anyway.)

**Comment by PeterDHabermehl** [comment]
PLEASE please please let us enable M500 at least in custom build firmware. I totally understand your intention and I also can accept breaking the appendix. But then at least the fw should build with EEPROM_SETTINGS enabled. I would like to set E-Steps, Extruder loading/unloading max. speed, and PID values. I don't want to take you responsibility on what I do, so I would break the appendix. But the build has to work with EEPROM_SETTINGS enabled.
Thank you so much and kind regards
Peter

**Comment by ogland** [comment]
@PeterDHabermehl You should read in the patch notes WHY they disabled it. It's not as easy as just enabling it.

**Comment by bobc** [comment]
Looking at the code, Prusa already stores several values in EEPROM, adding new ones is quite easy. I don't understand Prusa's reluctance to maintain features that already exist in Marlin and people widely rely on.

**Comment by ntmaster26** [comment]
Please please !! :)

**Comment by dcs3473** [comment]
Yes Please...

**Comment by d-zalewski** [comment]
New Mini owner with BondTech extruder and is upgrade. Please make this happen.

**Comment by bergh-io** [comment]
Yes, we need this :) Any info about if, and if so when, this might me released?

**Comment by JohnnyDeer** [comment]
Work on hidden menu for BondTech upgrade is in progress, will be in one of next releases.

**Comment by Pcgrande87** [comment]
yes please !

**Comment by sayeghr** [comment]
Is there any update on this issue? I’d really like to upgrade my extruder but am concerned the software doesn’t support it.

**Comment by Pcgrande87** [comment]
@sayeghr yes I made a firmware,

**Comment by sayeghr** [comment]
> @sayeghr yes I made a firmware,

What do you mean?

**Comment by padigree** [comment]
Would be glad if this could implemented soon. It's a confusing to use different start g codes for every prusa I have, also it's difficult to sync this on every machine I slice with..

**Comment by padigree** [comment]
Are there any news if it could be implemented in the next firmware?

**Comment by Czarnyszarf** [comment]
Any updates? Commits about this feature?

**Comment by stickybyte** [comment]
As I had seen in the source code, there seems to be a new menu item called „EEPROM“. Could be the menu @josefprusa talked about?
Maybe he can give more infos, if the feature will be part of the next release. I need it too...

**Comment by Czarnyszarf** [comment]
Im more intrested in hotend PWM fan speed - it may be the solution for Bondtech heatbreak problems.

Also it would improve cooling on modified minis with v6 hotends , they run pretty hot due to inadequate cooling

**Comment by s-taylor** [comment]
🙏 pretty please allow this. 3d printing is really a hobbiest discipline, and it's expected that people are going to tinker with their printers. Prusa knows this and supports this, they still provide customer support for modded printers so it's a logical step to support this. People are honestly more likely to generate bad prints and contact support because this feature is not baked in.

**Comment by Czarnyszarf** [comment]
any updates ?

**Comment by padigree** [comment]
2 1/2 more months are gone..

**Comment by PeterDHabermehl** [comment]
Break the appendix...-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 17.02.21, 11:19 schrieb padigree <notifications@github.com>:

   
  2 1/2 more months are gone..

**Comment by SteeeveAT** [comment]
Just to push this up, and in hope Josef will realize this soon.

**Comment by Czarnyszarf** [comment]
bump

**Comment by SHAXperiment** [comment]
Totally agree. Changing the E-Steps would be amazing. +1

**Comment by jayseeee** [comment]
Any news on this M500 issue? I also want to be able to change the esteps and the PID values and store them into EEPROM.

**Comment by BzuciakCZ** [comment]
#metoo Waiting so long to be able M500. No need special firmware for me. Just be able to store ESTEPS and PID.

**Comment by Aquaerics** [comment]
we want the UPDATE now :-)

**Comment by BzuciakCZ** [comment]
Hi guys. I just got an compromising idea. What about create support for post-start gcode, in which we can put our own initial values.
Something like AUTOEXEC.gcode :-)
Firmware and EEPROM will remain intact and if you mess something in that gcode, you simply remove USB stick and restart.

This might be useful not only for Bondtech modifications, but for many more
features bound to certain USB stick with distinct AUTOEXEC.gcode

I hate running my start gcode manually each time I want to load filament after printer start.

What do you think of this?

**Comment by derenma** [comment]
@BzuciakCZ I like that idea in general! Even if M500 is never enabled (and I think I have seen the code changes for it, but not sure) your idea could be useful in a number of ways, for sure. Thumbs up!

**Comment by Czarnyszarf** [comment]
Still no updates?  It's disappointing

**Comment by BogdanH59** [comment]
I got my MINI+ about two weeks ago, which I've upgraded with Bondtech extruder & heatbreak during assembly. Reason being, I just wished MINI to give best possible results and to avoid unnecessary hassle in the future. But sadly, later I realized one can't upgrade MINI in a comfortable way, because it's impossible to store necessary G-code into EEPROM.
And even worse: because latest MINI's are delivered with modified board, it's also impossible to use custom firmware anymore. Not that I'm really interested in custom firmware by itself -but I could at least store G-code.
Yes, MINI works as expected, but so do many other cheaper 3D printers. Needless to say that I'm a bit disappointed in this regard.
I think this issue should be solved by Prusa as soon as possible.

**Comment by derenma** [comment]
Well, you ain't wrong.

Prusa has been working on this issue, and I have been following most of the
code updates like a hawk.

I am speculating that most of the issues will be resolved after the next
board version.

**Comment by Czarnyszarf** [comment]
> 
> Well, you ain't wrong. Prusa has been working on this issue, and I have been following most of the code updates like a hawk. I am speculating that most of the issues will be resolved after the next board version.
> […](#)


Where I can find info about that new board and what's happening ?

**Comment by derenma** [comment]
You need to track the commits to the firmware, honestly.

**Comment by BogdanH59** [comment]
Correction related to my previous post.
Explanation:
Per [Prusa documentation](https://www.help.prusa3d.com/en/article/flashing-custom-firmware-mini_14), appendix on board must be removed (yeah, I know) and jumper must be used. Because new board is missing one of three pins (and printer doesn't boot if jumper is used on remaining two pins), I assumed one can't load custom (non-signed) firmware anymore.
As it turned out, custom firmware can be loaded without using jumper. Prusa should mention that in documentation though.

**Comment by pkg2000** [comment]
@BogdanH59 Prusa has updated their documentation with a note on this. It will see a larger overhaul to make it more future-proof in terms of hardware revisions.

**Comment by matthewlloyd** [comment]
Anyone following this issue may be interested to know that I just released custom firmware that adds a menu option to configure e-steps, with presets for the Bondtech extruder with and without reversed wires, amongst other goodies:

http://github.com/matthewlloyd/Llama-Mini-Firmware#readme

**Comment by enganear** [comment]
Thanks!!!

Stephen Chapman
Author - The Stonehenge Rift

**Comment by ogland** [comment]
Cool @matthewlloyd

How did you fix the eeprom desync that made Prusa disable saving to eeprom in the first place?

**Comment by matthewlloyd** [comment]
> How did you fix the eeprom desync that made Prusa disable saving to eeprom in the first place?

I couldn't find any specific details on the mysterious EEPROM desync (just [the patch notes](https://forum.prusaprinters.org/forum/general-discussion-announcements-and-releases/4-0-5-firmware-for-original-prusa-mini-2/) where they say Marlin EEPROM was causing "synchronization issues," and [this issue](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/364) where they say the values "were written inconsistently") so it's hard for me to say.

What I can say is that I didn't reenable Marlin EEPROM settings in Llama, I just followed Prusa's convention of moving the relevant settings into a proprietary section of the EEPROM. So I expect the llama has pronked right over whatever issues there were. :llama:

**Comment by PippoAe** [comment]
I'd love to see a menu that allows to change settings if the bondtech extruder is installed.

**Comment by JohnnyDeer** [comment]
Finally we released FW with promised hidden menu. We are sorry it took so long to develop this function. 
All you need to know is in the release notes. You can find new RC and try it here https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.3.3-RC.
Thank you all for patience.

**Comment by ogland** [comment]
That's great! Do consider adding a feature to use the heatsink fan at 100% too, since many users are having issues with heatcreep.

**Comment by BogdanH59** [comment]
Great news indeed! Even I already removed appendix (lost warranty), I still think added features might be useful for me one day.

I assume, many who upgrade the extruder also decide for (Bondtech) heatbreak upgrade. It's known that in this case different PID values are required. That means, to have exact PID values on startup, one still needs modified firmware (or run PID G-code after power on, or after factory reset).
Yes, we can run PID calibration which will be kept in memory (until reset)... But as Bondtech heatbreak has became a "standard" upgrade, it would be nice to have an **Heatbreak: Prusa / Bondtech** option in **HW Settings**. In my opinion this option would be more useful than **Extruder direction** (in case there's limited space on display).

**Comment by anttikarhu** [comment]
Hoping to see support for the Bondtech heatbreak in the official firmware in the future :) 

Workarounds of modifying Prusa Slicer printer profiles or running some gcode after every boot both work, but are just workarounds. Using default profiles is easy to use and maintain, and running custom gcode is easy to forget :)

**Comment by enganear** [comment]
Install the Llama firmware, it already has the ability to store PID values
in addition to esteps.

Stephen Chapman
Author - The Stonehenge Rift

**Comment by derenma** [comment]
I like warranties, customer support and that Prusa has dozens of printers
to test software updates on. That's just me though.

Was considering buying a second buddy board to mod though...

**Comment by JustAnother1** [comment]
@derenma Why not mod now and buy a second buddy board once you need support?

**Comment by Aquaerics** [comment]
I think it's a shame that it took so long. I have one of the first batch prusa minis. At the start they said you get weekly firmware updates for the new feature. Than they forbid to use the normal gcode feature to store the steps and the PID values. And now it takes month to get a fancy menue to change it. Normaly they should fixed the gcode storing and it would be easy for everyone. 
I had breaked my board to get this feature. And now i have to press the reset erverytime to start right. So i'm not amused that it took so long. 
I think prusa should update the mini that the print quality is the same or better than the mk3. Since it has the newer hardware base.

**Comment by derenma** [comment]
I am not speaking for Prusa, but there were quite a few underlying issues
that needed to get resolved.

There were some massive EEPROM read/write issues as well as some USB driver
issues that had to get resolved first. These two subsystems had to be fixed
first. I think.

Development work generally does not work out as expected.

**Comment by Aquaerics** [comment]
I'm a software developer too. So i think bug fixing is very important. For the MK3 there were many mechanical updates. For the prusa they took time to get a new level sensor. But they should have noticed it first that the old one did not work as expected. It's seems that the cost range was the only thing that matters to design the mini. For me it woud be better if it cost 200 euros more, and than it can print like the mk3 or better. So it had bondtech extruder and a good printer head out of the factory. 
There are many cool feature in the mini, so why don't make it a realy good printer?

**Comment by cnEUL** [comment]
the new firmware supports the bondtech extruder. i am using it and it works.

**Comment by Czarnyszarf** [comment]
I know, I mean heatsink fan speed

**Comment by Eldenroot** [comment]
Any update from devs for Bondtech heatbreak? Please!

**Comment by Prusa-Support** [comment]
Sorry for the late reaction, I was reviewing a few aspects with the rest of the team.

For clarity now, allow me to sum up your current requests.
- Support for Bondtech/custom heat-breaks, in a similar fashion as customizable extruder settings.
- Compatibility with custom PID settings. I guess this would also address Bondtech/custom heat-breaks incompatibility problems.
- An option to enable 100% hotend fan speed (probably something like AltFan on MK3).

Honestly, I'm not sure if these features are necessary.
- To address the first two points, our tests proved our MINI thermal regulation to be suitable for custom heat-breaks (see [Buddy FW 4.3.3](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.3.3)), rendering specific heat-break settings and custom PID settings unnecessary (nonetheless, we got other similar requests [#1341](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1341), [#2401](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2401)).
- To address the last point, heat-creeps are most often caused by factors other than the hotend fan running at regular, safe and adequate speed as per our defaults (not 100%).

Regardless of this, I'm taking notes and passing them along to the developers.
The issue will stay open, and our developers will do their consideration about these quite popular requests.

Michele Moramarco
Prusa Research

**Comment by Eldenroot** [comment]
@Prusa-Support - Hi, thank you for your reply!

I think that Prusa firmware should support these:

- Hotend fan speed: Adds a menu option to unlock the hotend fan speed and increase it from the Prusa Firmware's default 38% to anywhere from 50-100% - this is a must have for other than stock fan
- Bondtech heatbreak PID settings

These two are missing and I think they are useful.

**Comment by BzuciakCZ** [comment]
Thanks for update Michele,
100% fan speed would be sooo coool!

We could use E3D Revo Micro original fan or Noctua silent fans without having to source 5V fan power from other pins of the mainboard. 

I believe it is small code change with great impact. 

Regards,
Zbynek

**Comment by ogland** [comment]
I would also like to add to this to please lower load/unload speed slighly since it seems that it's slightly too fast for the motor/mcu to handle when using Bondtech esteps. Maybe even a load/unload length and speed option in hwmenu.

**Comment by Prusa-Support** [comment]
Thank you again for your suggestions.
Our developers will look into this.
Also please notice we are talking about the use of 3rd party components so, in the meantime, you may consult with the author of the mod or the parts vendor. You can even get in touch with other adopters of the mod among the community on forums (may our forum.prusa3d.com), as they may have tips, workarounds and experience in general to share.

Michele Moramarco
Prusa Research

**Comment by ogland** [comment]
@Prusa-Support the only workaround with good UX for all these issues would be custom firmware, but that breaks warranty so not really a viable workaround.

**Comment by Prusa-Support** [comment]
True. As a company, we can't take legal responsibility for the use of third-party components, and we can't even vouch for them.
The software and the product remain Open Source though, so modfing the firmware is legit but you do it at your risk.

Michele Moramarco
Prusa Research

**Comment by ogland** [comment]
@Prusa-Support exactly, so the only real and simple solution in good UX would be to add these simple features to the menu. I don't really see a single reason not to do that, but I can see many reasons for not removing them in the first place.

Starving the heatsink cooling may be good for noise, but as we can see in forums and groups many are having heatcreep. So I think it's worth testing 100% speed at least :)

**Comment by BzuciakCZ** [comment]
100% true Olof!On 10. 11. 2022, at 14:55, ogland ***@***.***> wrote:﻿
@Prusa-Support exactly, so the only real and simple solution in good UX would be to add these simple features to the menu. I don't really see a single reason not to do that, but I can see many reasons for not removing them in the first place.
Starving the heatsink cooling may be good for noise, but as we can see in forums and groups many are having heatcreep. So I think it's worth testing 100% speed at least :)

**Comment by Czarnyszarf** [comment]
I appove this, it was a year already..please do something with that!

**Comment by FabianMPunkt** [comment]
Is there any update on the 38% fan speed situation yet?
Since this issue is still open, my guess is that the dev team still has this on their list?
I really hope we can get an adjustable fan speed, the same way we can adjust E-Steps. That would make it possible to install a much quieter Noctua fan, and still get enough cooling to prevent heat-creep.

**Comment by SunshineSupremo** [comment]
:) Re-posting here as well: 

Greetings everyone; just in case anyone else has still been struggling to find the answers to this issue, I thought I would post this info, which was profoundly helpful to me in solving it for myself: I asked BondTech about the best way to get their extruders working with the MK3.5S, and they referred me to this link, and said to use 830 E-steps...

https://help.prusa3d.com/article/experimental-settings-mk4-s-mk3-9-s-mk3-5-s-xl-mini_264396

Some thoughts: the 830 number is supposed to be based on 16 microsteps, and also on the BondTech gearing being 3:1 compared to Prusa's 1:1... my printer was resetting its E-steps to 266 no matter how many ways I tried to M500 that $#!+, which would imply that perhaps my exact number is 798 (aka 266*3), but when I did the ol' 100mm extrusion test, I came out with 906 as my subjective requirement. All three of those numbers, in my case, seem to print just great (especially compared to whatever time-guzzling mess it was making before). Your mileage may vary and it is probably still worth fine-tuning accordingly, but this should get you started. Some forum users say the MK3.9/MK4 extruder motors are set at 32 microsteps, so possibly those need a number more like 415 for the E-steps, but I cannot vouch for that: do your own research as always, and make changes at your own risk ("...but what if the risk is that it starts working properly?")...

ALSO, in my case, probably simply due to the FW updates that have happened since Prusa posted that article, the menu mentioned in the above article was not "secret," it was just under Settings > Hardware, on the printer's control screen.

Also, there is a box there that just says "Make it work properly," which you should consider checking. 

Just kidding. But in the immortal words of Syd Barrett, what exactly IS a joke?

You're so close! Good luck!!!
