### ISSUE TITLE
[ENHANCEMENT]Validate GCode Input for Invalid Characters

### ISSUE THREAD

**Issue by 4nthonylin** [prusa3d/Prusa-Firmware-Buddy#830]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]
**Optional upgrades** - [Filament Runout Sensor]

**Is your suggested improvement related to an existing problem? Please describe.**
I had a corrupted file saved to my flash drive however the Prusa Mini will attempt to print it even if it's invalid input. This ultimately caused the print to fail.
![image](https://user-images.githubusercontent.com/4007580/90970284-cc8a8680-e4b7-11ea-8aaa-26267291dcff.png)

I have attached an example gcode diff of an invalid version on the left and correct on the right. This was most likely due to me prematurely pulling the usb out. I did re-export however it seem to not overwrite the corrupted characters.
![image](https://user-images.githubusercontent.com/4007580/90970250-4a01c700-e4b7-11ea-99fb-2378550f6cf7.png)

**Describe the expected functionality**
Prusa Mini should either
a. Validate the entire GCode contains only valid characters or 
b. As soon as the parser sees an invalid character (only accept alphanumeric characters with periods etc.) Fail the print by stopping and showing an error message to the GCode line and column with the invalid character.

**Comment by derenma** [comment]
I am betting a corrupt USB drive which is why the characters were not overwritten.  You can see other severe errors like "Mr04 Q1250" which is supposed to be "M204 S1250"

Simply doing a check for invalid characters is good anyway, but it would not fix your issue completely.

**Comment by JohnnyDeer** [comment]
Hi @4nthonylin this is a planned feature on the MINI.

**Comment by DRracer** [comment]
@4nthonylin we are working on a complete recheck of the input G-code because such corruption scenarios can happen. The MINI will be able to verify (lexically) the input G-code file at speeds of ~900KB/s based on what it can "suck" through the USB interface.
Since this can take a lot of time (but better than having a failed print), we are investigating options how to make this as user friendly as possible

**Comment by murk-sy** [comment]
Found this issue since I'm having some corruption related problems so I'd like to give my 2 cents.

Checksums are likely the best candidate for ease of implementation.

One thing I'd like to acknowledge before going into detail is the 2 types of errors:

1. Read error, which may be recoverable (by re-reading the affected file), but may not be detected ahead of time, and
2. Data corruption, which is unrecoverable (by re-reading the affected file), but can be detected ahead of time


I have encountered both read errors (see #1793 where ABL was run during a print at a specific point, but only sometimes) and data corruption.

### The most useful piece of information would be that there was *some* read related error, even if the print fails.

Rather than trying to investigate a printing issue, which could mislead you into believing it's related to slicing, print adhesion, or something else, it would be immediately evident that the storage device is the issue. There may have already been many read errors/corruption that were entirely undetected by the end user, as they may have affected only non-extrusion gcode.

Even if errors are only detected (perhaps under some threshold), there may be some benefits to continuing to print:
[+] Warns user of storage device issues even if parts themselves were unaffected
[+] Can save a lot of filament if multiple parts are being printed and only 1 is visually affected
[-] Can waste a lot of filament if a single part is being printed and visuals are very important or if it ends with spaghetti 


After a print is finished and errors were detected, ideally the user would receive a notification about it.
For example:
> 14 recoverable errors occured when reading gcode.
> Consider replacing storage device to avoid printing issues.
> [OK]

> 4 unrecoverable errors occured when reading gcode.
> 2 recoverable errors occured when reading gcode.
> Storage device may be irrepairably corrupt or damaged. Consider replacing storage device to avoid printing issues.
> [OK]
